name: Docker
on: [workflow_dispatch]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container: 
            image: node:23.11-alpine3.20
           # credentials:
            #username
            #pswd
            env:
                API_URL: some-url.com
            ports:
                - 80
            #volumes:
           # options: --cpus 1
        steps:
            - name: Log Node & OS versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: echo $API_URL    
            - name: create a file
              run: echo 'some text' > text.txt
            - name: container in a step
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: /usr/local/bin/node 
                args: -p 2+3
            
            - name: log node version
              uses: docker://node:18.16-alpine3.17
              with:
                args: -v
            - name: show file contents
              uses: docker://node:18.16-alpine3.17
              with:
                entrypoint: cat
                args: text.txt

