name: expressions and context
on: [push, pull_request, issues, workflow_dispatch]
run-name: "expression and contexts by @${{ github.actor }} , event: ${{ github.event_name }}"

jobs:
    using-expression-context:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Expression
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'this is string' }}
                echo ${{ null }}
                echo ${{ 1 > 2 }}
                echo ${{ true }}
                echo ${{ 'string' == 'String' }}
                echo ${{ true && false }}
                echo ${{ true || (false && true) }}
            - name: Dump contexts
              run: |
                echo '${{ toJson(github)}}'
                echo '${{ toJson(job)}}'
                echo '${{ toJson(secrets)}}'    
                echo '${{ toJson(steps)}}' 
                echo '${{ toJson(runner)}}' 